//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFramworkFinalProject2
{
    using System;
    using System.Collections.Generic;
    
    public partial class DismissalNotice
    {
        public int dismissal_id { get; set; }
        public System.DateTime dismissal_date { get; set; }
        public int dismissalDept_id { get; set; }
        public int dismissalStore_id { get; set; }
        public int dismissalUser_id { get; set; }
        public int dismissalClient_id { get; set; }
        public string Code { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<int> totalPrice { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Department Department { get; set; }
        public virtual Store Store { get; set; }
        public virtual User User { get; set; }
        public virtual C_itemsDetails C_itemsDetails { get; set; }
    }
}
