//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFramworkFinalProject2
{
    using System;
    using System.Collections.Generic;
    
    public partial class permitionItem
    {
        public int permItem_id { get; set; }
        public int permition_id { get; set; }
        public System.DateTime item_date { get; set; }
        public int item_price { get; set; }
        public int item_periodValidity { get; set; }
        public string code { get; set; }
        public int Store_Id { get; set; }
        public System.DateTime ProductionEnd { get; set; }
        public Nullable<int> quantity { get; set; }
    
        public virtual C_itemsDetails C_itemsDetails { get; set; }
        public virtual Store Store { get; set; }
        public virtual SupplyPermission SupplyPermission { get; set; }
    }
}
