//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFramworkFinalProject2
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupplyPermission
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SupplyPermission()
        {
            this.permitionItems = new HashSet<permitionItem>();
        }
    
        public int permission_id { get; set; }
        public System.DateTime permission_date { get; set; }
        public int permSupplier_id { get; set; }
        public int permDept_id { get; set; }
        public int permStore_id { get; set; }
        public int permUser_id { get; set; }
        public string code { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<int> totalprice { get; set; }
    
        public virtual Department Department { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<permitionItem> permitionItems { get; set; }
        public virtual Store Store { get; set; }
        public virtual Supplier Supplier { get; set; }
        public virtual User User { get; set; }
        public virtual C_itemsDetails C_itemsDetails { get; set; }
    }
}
