//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFramworkFinalProject2
{
    using System;
    using System.Collections.Generic;
    
    public partial class transactionItem
    {
        public int trans_id { get; set; }
        public int StoreSend { get; set; }
        public int StoreRecive { get; set; }
        public int EmployeeSend { get; set; }
        public int EmployeeRecive { get; set; }
        public System.DateTime Date { get; set; }
        public string Code { get; set; }
        public int Quantity { get; set; }
    
        public virtual C_itemsDetails C_itemsDetails { get; set; }
        public virtual Store Store { get; set; }
        public virtual Store Store1 { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
